### ISSUE TITLE
Idea: Premade APKs for included lite apps

### ISSUE THREAD

**Issue by jversusk** [chimbori/hermit-lite-app-example#1]
It would be nice if we could simply download such APKs for lite apps included in Hermit, at least the popular ones. No need to make the downloads available in the app itself, could just add them to the releases here.

**Comment by chimbori** [comment]
Yes, we are considering that! For custom pre-built APKs , we want to embed all the settings into the APK itself (compared to the current APK sample where only the target URL is included). Once we have that, we’ll offer downloadable APKs through here.

**Comment by chimbori** [comment]
There’s very little demand for this feature, so we’ll continue with the current model of providing Hermit Lite App configs through the Library, and the APKs optional for anyone to generate via this repo.
