### ISSUE TITLE
adding hermit to the resulting bundle

### ISSUE THREAD

**Issue by stevebbs** [chimbori/hermit-lite-app-example#2]
I've successfully produced an apk using hermit-lite-app-example with Android Studio. When it plays it says HERMIT needs to be installed which I've done and all is good. I'm new to working with the android platform. Is there a way of bundling HERMIT with the resultant app from Android Studio to avoid folk I share my APK with having to do 2 installs?

**Comment by chimbori** [comment]
Excellent, glad you got this working!

We don’t recommend bundling Hermit, for several reasons:

- This is only required the first time. For all subsequent Lite Apps, you can have a much smaller APK size for each individual Lite App.
- By not bundling Hermit itself, users can receive updates directly from us via the Play Store. Keeping Hermit updated is important to receive the latest features, bug fixes, and security issues.
- From a licensing perspective, Hermit is not licensed for distribution. We would like to make sure that users directly download and update Hermit from us. For any Lite Apps created by you via this source code, you will retain all rights to distribution.

**Comment by stevebbs** [comment]
First of all a big THANK you for your detailed answer - and also, of-course, for Hermit. Sorry to take advantage of your kind help but I have three further questions! 

1. when setting up the APK in Android Studio is there a way to set the parameters (e.g. in AndroidManifest.xml) so that when the recipient opens my app, Hermit automatically opens in a. Desktop Mode b. Frameless c. Full-screen ?
2. my app switches between showing a RTMP youtube embedded feed to a WebRTC live feed. In Chrome (on Android) I don't have a problem with autoplay in either - but Hermit (in both Desktop mode and non-desktop mode) stops autoplay until the user manually changes either play or sound. Strangely for the WebRTC feed it remembers after the first time and allows auto - but for the youtube stream it has to be manually allowed every time. Is there any way of setting Hermit to autoplay (similar to the "sites can play sound" setting in Chrome Windows browser or the "autoplay flag" in Edge)?
3. when my APK installs on an Android without Hermit - it prompts to install Hermit (seemingly the intention at this point is to direct the user to PlayStore) - but when the button to continue is pressed it doesn't do anything. Is this a fault, a problem with the version of android, or intended?

MANY thanks again

**Comment by stevebbs** [comment]
One other thing that's appeared during testing FYI ...my Android 11 has no problem (Hermit doesn't need to be opened at all - it just sits in the background). But my wife's Android 8.1.0 (newly updated) works fine on first entry after installing the app and Hermit... but as from the 2nd entry to the app it can't record any cookies. I either have to re-install hermit every time - or I've found that if I "Create a Lite App" from my app then it records this in Hermit and everything works fine from then on. Just to let you know - unless you know of a better workaround. The platform is really great - especially the ability to go full-screen and frameless. Just a few things to set up as work-arounds to begin with. Thanks again.
